### ISSUE TITLE
What is the document's goal?

### ISSUE THREAD

**Issue by martinduke** [mirjak/draft-shmoo-online-meeting#21]
I'm a little confused if this document is meant to report on previous experience with online meetings during the pandemic, or provide a set of common practices that should be a baseline for further experimentation.

Perhaps this should be a BCP?

I would like to do an editorial pass, but I fear I can't until I know the answer to this question.

**Comment by mirjak** [comment]
discussed at ietf-115 and addressed by Pr #22
