### ISSUE TITLE
Set start times

### ISSUE THREAD

**Issue by martinduke** [mirjak/draft-shmoo-online-meeting#3]
The current convention of "noon local time" is semi-arbitrary, and in the event of a planned online meeting, there may be no "local time" to use.

On the list, we discussed the 0000/0800/1600 UTC rotation. Mirja suggested 0500/1200/2100 as slightly more optimized, and I'm happy to take that suggestion.

PR to follow.

**Comment by mirjak** [comment]
Thanks. I was planning to update the draft and add a proposal anyway (just this week id super full as there is a holiday tomorrow); so a PR would be more than welcome!

Here is as a reference what I originally proposed to the list:

```
So I think it might actually be worth to think about picking three time slots with 8h offset and rotated between those rather than orienting too much towards the local time. Participants are not equally distributed over all time zone; and I don’t mean that some zones have more people than other but that there are time zones in the world where there is no land and as such no-one lives. And so not all starting times work equally well. This is more or less one of the reason why we didn’t start a fixed local time for the last couple of meetings but shifted one hour in one or the other direction (to basically decrease the overall pain at least a bit).

I would propose the following slots (with the limitation that the first slot always has to be in summer to work a bit better for both China and Australian/New Zealand). I propose the slots because I think they are probably as good as possible for most of the participants. However, they are more or less also reflecting the start at 13:00 in either Europe, China, or west coast US time we used so far. Or you can also see them to start at 5:00 or 6:00 in either Europe, China, or West Coast USA.

Berlin (Germany)	14:00:00	CEST	UTC+2 hours
Beijing (China)		20:00:00	CST	UTC+8 hours
Sydney (Australia)	22:00:00	AEST	UTC+10 hours
Wellington (New Zealand)00:00:00	NZST	UTC+12 hours
New York (USA		08:00:00	EDT	UTC-4 hours
San Francisco (USA)	05:00:00	PDT	UTC-7 hours
UTC (GMT)		12:00:00			

Berlin (Germany)	22:00:00	CET	UTC+1 hour
Beijing (China)		05:00:00	CST	UTC+8 hours
Sydney (Australia)	08:00:00	AEDT	UTC+11 hours
Wellington (New Zealand)10:00:00	NZDT	UTC+13 hours
New York (USA)		16:00:00	EST	UTC-5 hours
San Francisco (USA)	13:00:00	PST	UTC-8 hours
UTC (GMT)		21:00:00		

Berlin (Germany)	06:00:00	CET	UTC+1 hour
Beijing (China)		13:00:00	CST	UTC+8 hours
Sydney (Australia)	16:00:00	AEDT	UTC+11 hours
Wellington (New Zealand)18:00:00	NZDT	UTC+13 hours
New York (USA)		00:00:00	EST	UTC-5 hours
San Francisco (USA)	21:00:00	PST	UTC-8 hours
UTC (GMT)		05:00:00
```

I came up with these slots by starring at this page for a while:

https://www.timeanddate.com/worldclock/meetingtime.html?day=8&month=12&year=2021&p1=204&p2=33&p3=240&p4=264&p5=179&p6=224&iv=0

But note that the picture looks slightly different if you select a date that is in EU/US winter time and AUS/NZ summer time.

**Comment by martinduke** [comment]
I would encourage us not to overthink the summer/winter thing. It's too complicated.

**Comment by mirjak** [comment]
The main point is that the mapping I provided above is only correct for northern hemisphere winter. I guess 20:00 UTC is probably slightly better in northern hemisphere summer than 21:00 UTC:

```
Berlin (Germany)	22:00:00	CEST	UTC+2 hours
Beijing (China)		04:00:00	CST	UTC+8 hours
Sydney (Australia)	06:00:00	AEST	UTC+10 hours
Wellington (New Zealand)08:00:00	NZST	UTC+12 hours
New York (USA)		16:00:00	EDT	UTC-4 hours
San Francisco (USA)	13:00:00	PDT	UTC-7 hours
Corresponding UTC (GMT)	20:00:00
```

However it's not a huge difference. But I think it would be good to note that this slot is preferred to be used in northern hemisphere winter.

**Comment by mirjak** [comment]
Actually, the 20:00 UTC time in summer is slightly worth for China, so maybe really not worth it...
