### ISSUE TITLE
The IETF Hackathon is part of the IETF Meeting

### ISSUE THREAD

**Issue by eckelcu** [mirjak/draft-shmoo-online-meeting#9]
Starting with IETF 108, the IETF Hackathon has been online only and run the entire week before the IETF meeting. The Hackathon, and its impact on the length of the IETF meeting, should be added to this draft. 
A work in progress reference that provides more detail is https://www.ietf.org/archive/id/draft-ietf-shmoo-hackathon-01.html#name-online-only.

**Comment by eckelcu** [comment]
The changes in https://github.com/mirjak/draft-shmoo-online-meeting/releases/tag/draft-kuehlewind-shmoo-online-meeting-02 addressed this. I believe this issue can be closed.

**Comment by martinduke** [comment]
Closing per Charles's comment
